trigger:
- main

# Agent VM image name
pool:
  name: 'mypool'

steps:
  - task: TerraformTaskV4@4
    displayName: "Terraform Init and apply"
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'Azure subscription 1(e9271524-7275-4e25-9b3f-f52f6a4e4cac)'
      backendAzureRmResourceGroupName: 'well-tarpon-rg'
      backendAzureRmStorageAccountName: 'vinayasdstorageacc'
      backendAzureRmContainerName: 'vinayasdcontainer'
      backendAzureRmKey: 'prod.terraform.tfstate'
    -script: |
          terraform init
          terraform apply -var-file="terraform.tfvars" -auto-approve